config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :transaction_data, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :patients do
    collection do
      # get :scan_smartcard
      post 'process_card_scan'
      get 'scan_smartcard' 
    end
    member do
      patch :check_in
      patch :check_out
    end
  end
  resources :settings
  resources :admins
  resources :manage_receptions
  resources :branches, only: [:index, :new, :create, :edit, :update, :destroy]
  devise_for :users
  resources :denialcodelists do
    collection do
      post :import
    end
  end
  resources :doctorlists, path: 'user'
  resources :transactions, only: [:index,:show] do
    collection do
        get 'download_report' 
      end
    post :fetch_transactions, on: :collection
  end
  root 'welcome#index'
end

app/models/branch.rb
class Branch < ApplicationRecord

  validates :username, presence: true, uniqueness: true
  validates :login, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :clinical_id, presence: true,uniqueness: true
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: %i[show edit update destroy]

  def index
  authorize Branch, :index? 
  @branches = Branch.page(params[:page])
  # @branches = Branch.all
  @branch = Branch.new
  end

  def show
  end

  def new
    @branch = Branch.new
  end

  def create
    @branch = Branch.new(branch_params)

    # Check if a branch with the same username, login, or clinical_id exists
    if Branch.exists?(username: @branch.username) || Branch.exists?(login: @branch.login) || Branch.exists?(clinical_id: @branch.clinical_id)
      return render_notification("A branch with this username, login, or clinical ID already exists.")
    elsif @branch.save
      redirect_to branches_path, notice: 'Branch was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @branch.update(branch_params)
      redirect_to branches_path, notice: 'Branch was successfully updated.'
    else
      redirect_to branches_path,  alert: "errors: #{@branch.errors.full_messages.join(', ')}"
    end
  end


  def destroy
    @branch.destroy
    redirect_to branches_path, notice: 'Branch was successfully deleted.'
  end

  private

  def render_notification(message, type: :notice)
    flash[type] = message
    respond_to do |format|
      format.html { redirect_to branches_path } 
      format.turbo_stream do
        render turbo_stream: turbo_stream.append(
          :notifications, 
          partial: "layouts/flash_notifications", 
          locals: { message: message, type: type }
        )
      end
    end
  end

  def set_branch
    @branch = Branch.find(params[:id])
  end

  def branch_params
    params.require(:branch).permit(:username, :login, :password, :clinical_id)
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/index.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    <h4 class="card-title">Branches</h4>
    <%= link_to " <i class='fa fa-arrow-left'></i> Back".html_safe, admins_path, class: "btn btn-secondry mb-3" %>
  </div>

  <div class="card-body">
    <!-- Button to trigger the modal -->
    <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#add-branch-modal">
      New Branch
    </button>

    <div class="table-responsive">
      <table class="table table-striped custom-table table-hover table-checkable order-column valign-middle">
        <thead class="text-primary">
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Eclaim_Username</th>
            <th>License_Number </th>
            <th class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @branches.each_with_index do |branch,index| %>
            <tr>
              <td><%= index + 1 %></td> 
              <td><%= branch.username %></td>
              <td><%= branch.login %></td>
              <td><%= branch.clinical_id %></td>
              <td class="text-center">
                <div class="d-flex justify-content-center">
                  <button type="button" class="btn btn-link btn-warning p-0 mx-3" data-toggle="modal" data-target="#edit-branche-modal-<%= branch.id %>">
                    <i class="fas fa-edit fa-lg"></i>
                  </button>
                  <%= button_to branch_path(branch), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link text-danger p-0" do %>
                     <i class="fas fa-trash-alt fa-lg"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
            <!-- Pagination -->
      <div class="d-flex justify-content-center mt-3">
        <%= paginate @branches, theme: 'bootstrap4' %>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="add-branch-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog bg-dark" role="document">
    <div class="modal-content bg-dark">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLongTitle">New Branch</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modal-body-content">
        <!-- Pass a new Branch instance to the form -->
        <%= form_with(model: Branch.new, url: branches_path, local: true) do |form| %>
          <% if form.object.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this branch from being saved:</h2>
              <ul>
                <% form.object.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="modal-body">
            <div class="form text-white-50 form-fields">
              <div class="form-row">
                <div class="form-group col-md-12">
                  <%= form.label :name %>
                  <%= form.text_field :username, class: "form-control" %>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group col-md-12">
                  <%= form.label :eclaim_username %>
                  <%= form.text_field :login, class: "form-control" %>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group col-md-12">
                  <%= form.label :eclaim_password %>
                  <%= form.password_field :password, class: "form-control" %>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group col-md-12">
                  <%= form.label :License_Number  %>
                  <%= form.text_field :clinical_id, placeholder: " (e.g., DHA-F-0090081)", class: "form-control" %>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= form.submit 'Save', class: 'btn btn-fill btn-info' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal for editing branch -->
<% @branches.each do |branch| %>
  <div class="modal fade" id="edit-branche-modal-<%= branch.id %>" tabindex="-1" role="dialog" aria-labelledby="editBranchModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content bg-dark">
        <div class="modal-header">
          <h5 class="modal-title" id="editBranchModalLabel">Edit Branch</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="modal-body-content">
          <%= form_with(model: branch, local: true, html: { multipart: true }) do |form| %>
            <% if form.object.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h5><%= pluralize(form.object.errors.count, "error") %> prohibited this branch from being updated:</h5>
                <ul>
                  <% form.object.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="modal-body">
              <div class="form text-white-50 form-fields">
                <div class="form-row">
                  <div class="form-group col-md-12">
                    <%= form.label :name %>
                    <%= form.text_field :username, class: "form-control" %>
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-group col-md-12">
                    <%= form.label :eclaim_username %>
                    <%= form.text_field :login, class: "form-control" %>
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-group col-md-12">
                    <%= form.label :eclaim_password %>
                    <%= form.password_field :password, class: "form-control" %>
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-group col-md-12">
                    <%= form.label :License_Number %>
                    <%= form.text_field :clinical_id, placeholder: " (e.g., DHA-F-0090081)", class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= form.submit 'Update', class: 'btn btn-fill btn-warning' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>