config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :transaction_data, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :patients do
    collection do
      # get :scan_smartcard
      post 'process_card_scan'
      get 'scan_smartcard' 
    end
    member do
      patch :check_in
      patch :check_out
    end
  end
  resources :settings
  resources :admins
  resources :manage_receptions
  resources :branches, only: [:index, :new, :create, :edit, :update, :destroy]
  devise_for :users
  resources :denialcodelists do
    collection do
      post :import
    end
  end
  resources :doctorlists, path: 'user'
  resources :transactions, only: [:index,:show] do
    collection do
        get 'download_report' 
      end
    post :fetch_transactions, on: :collection
  end
  root 'welcome#index'
end

app/models/denialcodelist.rb
class Denialcodelist < ApplicationRecord
  require 'roo'

  validates :denial_code, presence: true
  validates :description, presence: true
  has_many :transaction_data, 
           foreign_key: 'denial_code', 
           primary_key: 'denial_code', 
           class_name: 'TransactionData'
  validates :effective_from, presence: true
  validate :effective_dates_order

  private

  def effective_dates_order
    if effective_to.present? && effective_from > effective_to
      errors.add(:effective_to, "must be after the effective_from date")
    end
  end
end

app/controllers/denialcodelists_controller.rb
class DenialcodelistsController < ApplicationController
  before_action :set_denialcodelist, only: [:edit, :update, :destroy]

  def index
    authorize :settings, :index?
    
    if params[:query].present?
      @denialcodelists = Denialcodelist.where('denial_code ILIKE ? OR description ILIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
    else
      @denialcodelists = Denialcodelist.all
    end

    @denialcodelists = @denialcodelists.page(params[:page])
    @denialcodelist = Denialcodelist.new
  end


  def import
    upload_file
  end

  def new
    @denialcodelist = Denialcodelist.new
  end

  def create
    @denialcodelist = Denialcodelist.new(denialcodelist_params)
    if @denialcodelist.save
      redirect_to denialcodelists_path, notice: 'Dental code was successfully created.'
    else
      redirect_to denialcodelists_path, alert: "errors: #{@denialcodelist.errors.full_messages.join(', ')}"
    end
  end

  def edit; end

  def update
    if @denialcodelist.update(denialcodelist_params)
      redirect_to denialcodelists_path, notice: 'Dental code was successfully updated.'
    else
      redirect_to denialcodelists_path, alert: "errors: #{@denialcodelist.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @denialcodelist.destroy
    redirect_to denialcodelists_path, notice: 'Dental code was successfully destroyed.'
  end

  private

  def upload_file
    if params[:file].present?
      file = params[:file]
      spreadsheet = Roo::Spreadsheet.open(file)

      header = spreadsheet.row(1)
      skipped_records = [] 
      imported_records = 0 

      (2..spreadsheet.last_row).each do |i| 
        row = Hash[[header, spreadsheet.row(i)].transpose]

        effective_from = row['Effective From'].is_a?(Date) ? row['Effective From'] : Date.parse(row['Effective From'].to_s)
        effective_to = row['Effective To'].present? ? Date.parse(row['Effective To'].to_s) : nil

        # Skip the record if the denial code already exists
        denial_code = row['Code']
        if Denialcodelist.exists?(denial_code: denial_code)
          skipped_records << denial_code
          next
        end

        Denialcodelist.create!(
          denial_code: denial_code,
          description: row['Description'],
          effective_from: effective_from,
          effective_to: effective_to
        )
        imported_records += 1
      end

      # Display a notice with the result of the import
      message = "File imported successfully. #{imported_records} records added."
      message += " Skipped #{skipped_records.count} duplicate records" if skipped_records.any?
      redirect_to denialcodelists_path, notice: message
    else
      redirect_to denialcodelists_path, alert: 'No file uploaded'
    end
  rescue StandardError => e
    redirect_to denialcodelists_path, alert: "Error importing file: #{e.message}"
  end

  def set_denialcodelist
    @denialcodelist = Denialcodelist.find(params[:id])
  end

  def denialcodelist_params
    params.require(:denialcodelist).permit(:denial_code, :description, :effective_from, :effective_to)
  end
end

app/helpers/denialcodelists_helper.rb
module DenialcodelistsHelper
end

app/views/denialcodelists/index.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    <h4 class="card-title">Dental Codes</h4>
    <%= link_to " <i class='fa fa-arrow-left'></i> Back".html_safe, settings_path, class: "btn btn-secondry mb-3" %>
  </div>

  <div class="card-body">
    <div class="d-flex justify-content-between">
    <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#add-denial-code-modal">
      New Dental Code
    </button>
    <%= form_with url: import_denialcodelists_path, method: :post, local: true, html: { multipart: true, id: "file-upload-form" } do |f| %>
      <div class="form-group">
        <!-- Hidden file input -->
        <%= f.file_field :file, id: "file-upload", class: "d-none", required: true, onchange: "submitFileForm()" %>
        <label for="file-upload" class="btn btn-primary">
          <i class="fas fa-upload"></i> Upload File
        </label>
      </div>
    <% end %>
    </div>
    <div class="table-responsive">
      <table class="table table-striped custom-table table-hover table-checkable order-column valign-middle">
       <thead class="text-primary">
        <tr>
          <th>#</th>
          <th>Dental Code</th>
          <th>Description</th>
          <th>Effective From</th>
          <th>Effective To</th>
          <th class="text-center">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @denialcodelists.each_with_index do |denial, index| %>
          <tr>
            <td><%= (index + 1) + (@denialcodelists.current_page - 1) * @denialcodelists.limit_value %></td>
            <td><%= denial.denial_code %></td>
            <td><%= denial.description %></td>
            <td><%= denial.effective_from&.strftime('%Y-%m-%d') %></td>
            <td><%= denial.effective_to&.strftime('%Y-%m-%d') %></td>
            <td class="text-center">
              <div class="d-flex justify-content-center">
                <button type="button" class="btn btn-link btn-warning p-0 mx-3" data-toggle="modal" data-target="#edit-denial-code-modal-<%= denial.id %>">
                  <i class="fas fa-edit fa-lg"></i>
                </button>
                <%= button_to denialcodelist_path(denial), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link text-danger p-0" do %>
                  <i class="fas fa-trash-alt fa-lg"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <!-- Pagination -->
      <div class="d-flex justify-content-center mt-3">
        <%= paginate @denialcodelists, theme: 'bootstrap4' %>
      </div>
    </div>
  </div>
</div>

<!-- Modal for creating a new denial code -->
<div class="modal fade" id="add-denial-code-modal" tabindex="-1" role="dialog" aria-labelledby="addDenialCodeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-dark">
      <div class="modal-header">
        <h5 class="modal-title" id="addDenialCodeModalLabel">Create New Dental Code</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modal-body-content">
        <%= form_with(model: @denialcodelist, local: true) do |form| %>
          <% if form.object.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h5><%= pluralize(form.object.errors.count, "error") %> prohibited this denial code from being saved:</h5>
              <ul>
                <% form.object.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="modal-body">
            <div class="form text-white-50 form-fields">
              <div class="form-row">
                <div class="form-group col-md-12">
                  <%= form.label :dental_code %>
                  <%= form.text_field :denial_code, class: "form-control", required: true %>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group col-md-12">
                  <%= form.label :description %>
                  <%= form.text_area :description, class: "form-control", required: true %>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= form.label :effective_from %>
              <%= form.date_field :effective_from, class: "form-control" %>
            </div>
            <div class="form-group col-md-6">
              <%= form.label :effective_to %>
              <%= form.date_field :effective_to, class: "form-control" %>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= form.submit 'Save', class: 'btn btn-fill btn-info' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% @denialcodelists.each do |denial| %>
  <div class="modal fade" id="edit-denial-code-modal-<%= denial.id %>" tabindex="-1" role="dialog" aria-labelledby="editDenialCodeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content bg-dark">
        <div class="modal-header">
          <h5 class="modal-title" id="editDenialCodeModalLabel">Edit Dental Code</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="modal-body-content">
          <%= form_with(model: denial, local: true, html: { multipart: true }) do |form| %>
            <% if form.object.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h5><%= pluralize(form.object.errors.count, "error") %> prohibited this denial code from being updated:</h5>
                <ul>
                  <% form.object.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="modal-body">
              <div class="form text-white-50 form-fields">
                <div class="form-row">
                  <div class="form-group col-md-12">
                    <%= form.label :dental_code %>
                    <%= form.text_field :denial_code, class: "form-control" %>
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-group col-md-12">
                    <%= form.label :description %>
                    <%= form.text_area :description, class: "form-control", rows: 3 %>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <%= form.label :effective_from %>
                <%= form.date_field :effective_from, class: "form-control", value: denial.effective_from %>
              </div>
              <div class="form-group col-md-6">
                <%= form.label :effective_to %>
                <%= form.date_field :effective_to, class: "form-control", value: denial.effective_to %>
              </div>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= form.submit 'Update', class: 'btn btn-fill btn-warning' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function () {
  const fileInput = document.getElementById("file-upload");

  // Update the label with the file name after selecting a file
  fileInput.addEventListener("change", function () {
    const fileName = fileInput.files[0]?.name || "Choose file";
    const fileLabel = document.querySelector("label[for='file-upload']");
    fileLabel.innerHTML = `<i class="fas fa-upload"></i> ${fileName}`;
  });
});

// Function to submit the form
function submitFileForm() {
  document.getElementById("file-upload-form").submit();
}

</script>