config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :transaction_data, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :patients do
    collection do
      # get :scan_smartcard
      post 'process_card_scan'
      get 'scan_smartcard' 
    end
    member do
      patch :check_in
      patch :check_out
    end
  end
  resources :settings
  resources :admins
  resources :manage_receptions
  resources :branches, only: [:index, :new, :create, :edit, :update, :destroy]
  devise_for :users
  resources :denialcodelists do
    collection do
      post :import
    end
  end
  resources :doctorlists, path: 'user'
  resources :transactions, only: [:index,:show] do
    collection do
        get 'download_report' 
      end
    post :fetch_transactions, on: :collection
  end
  root 'welcome#index'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.erb
<h2 class="mt-4 text-center text-primary">Settings</h2>

<div class="shadow-lg p-4 rounded bg-dark mt-3">
  <div class="list-group">
    <!-- Doctor List -->
    <%= link_to doctorlists_path, class: "list-group-item list-group-item-action bg-dark text-white d-flex align-items-center mb-2 border-0 rounded-lg shadow-sm hover-zoom" do %>
      <i class="fas fa-users mr-3 fs-4"></i>
      <span class="fs-5">Users</span>
    <% end %>
    <!-- Manage Reception -->
    <%#= link_to manage_receptions_path, class: "list-group-item list-group-item-action bg-dark text-white d-flex align-items-center mb-2 border-0 rounded-lg shadow-sm hover-zoom" do %>
      <%# <i class="fas fa-receipt mr-3 fs-4"></i> %>
      <%# <span class="fs-5">Reception</span> %>
    <%# end %>
    <!-- Denial Codes -->
    <%= link_to denialcodelists_path, class: "list-group-item list-group-item-action bg-dark text-white d-flex align-items-center mb-2 border-0 rounded-lg shadow-sm hover-zoom" do %>
      <i class="fas fa-file-alt mr-3 fs-4"></i>
      <span class="fs-5">Dental Codes</span>
    <% end %>
  </div>
</div>