config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  resources :transaction_data, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :patients do
    collection do
      # get :scan_smartcard
      post 'process_card_scan'
      get 'scan_smartcard' 
    end
    member do
      patch :check_in
      patch :check_out
    end
  end
  resources :settings
  resources :admins
  resources :manage_receptions
  resources :branches, only: [:index, :new, :create, :edit, :update, :destroy]
  devise_for :users
  resources :denialcodelists do
    collection do
      post :import
    end
  end
  resources :doctorlists, path: 'user'
  resources :transactions, only: [:index,:show] do
    collection do
        get 'download_report' 
      end
    post :fetch_transactions, on: :collection
  end
  root 'welcome#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  require 'nokogiri'
  require 'base64'

  before_action :set_to_date

  def index
  end

  def download_report
    username = params[:username]
    report_type = params[:report_type]
    @from_date = params[:transaction_from_date].presence
    @to_date = params[:transaction_to_date].presence

    @transactions = if username.present?
                      branch = Branch.find_by(username: username)
                      if branch
                        clinical_id = branch.clinical_id
                        scope = TransactionData.where("sender_id = ? OR receiver_id = ?", clinical_id, clinical_id)
                        scope = scope.where("denial_code IS NOT NULL") if report_type == "rejection"
                        
                        if @from_date && @to_date
                          scope = scope.where(transaction_date: Date.parse(@from_date).beginning_of_day..Date.parse(@to_date).end_of_day)
                        end
                        scope
                      else
                        TransactionData.none
                      end
                    else
                      TransactionData.none
                    end

    respond_to do |format|
      format.html
      format.xlsx do
        report_name = report_type == "rejection" ? "rejection_report" : "full_report"
        render xlsx: report_name, template: "transactions/report"
      end
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
    @xml_doc = Nokogiri::XML(@transaction.xml_content)
    @claims = @xml_doc.xpath('//Claim')
  end

  def fetch_transactions
    username = params[:username]
    return render_notification("Username is required.") if username.blank?

    branch = Branch.find_by(username: username)
    return render_notification("Branch with this username not found.") unless branch

    login, password = branch.login, branch.password
    transaction_params = fetch_transactions_params.except(:password, :authenticity_token, :commit, :username)

    # Check if the transaction already exists with the matching login, from_date, and to_date
    if transaction_exists?(login, transaction_params)
      return render_notification("No new request. Same parameters already exist in the database.")
    end

    # Create and save the new SearchTransaction with the provided parameters
    search_transaction = SearchTransaction.new(transaction_params.merge(login: login))

    if search_transaction.save
      # Pass the search_transaction_id to the job and queue it for background processing
      ProcessTransactionsJob.perform_later({
        login: login,
        password: password,
        transaction_from_date: params[:transaction_from_date],
        transaction_to_date: params[:transaction_to_date],
        direction: 2, 
        transaction_id: 8, 
        transaction_status: 1, 
        min_record_count: -1,
        max_record_count: -1,
        sequence: [
          { direction: 2, transaction_id: 8, transaction_status: 2 }, 
          { direction: 1, transaction_id: 2, transaction_status: 1 }, 
          { direction: 1, transaction_id: 2, transaction_status: 2 }
        ],
        search_transaction_id: search_transaction.id  # Include search_transaction_id in the job
      })

      render_notification("Request parameters saved and transaction files will be processed in the background.")
    else
      render_notification("Failed to save request parameters: #{search_transaction.errors.full_messages.join(', ')}")
    end
  end

  private

  def fetch_transactions_params
    params.permit(
      :username, :login, :password, :transaction_id, :direction,
      :transaction_status, :min_record_count, :max_record_count,
      :transaction_from_date, :transaction_to_date, :authenticity_token, :commit
    )
  end

  def transaction_exists?(login, params)
    SearchTransaction.exists?(
      login: login,
      transaction_from_date: params[:transaction_from_date],
      transaction_to_date: params[:transaction_to_date]
    )
  end

  def render_notification(message, type: :notice)
    flash[type] = message
    respond_to do |format|
      format.html { redirect_to root_path } # Adjust to redirect back or handle however needed
      format.turbo_stream do
        render turbo_stream: turbo_stream.append(
          :notifications, 
          partial: "layouts/flash_notifications", 
          locals: { message: message, type: type }
        )
      end
    end
  end

  def set_to_date
    if params[:transaction_from_date].present? && !params[:transaction_to_date].present?
      to_date = params[:transaction_from_date].to_date + 3.months
      params[:transaction_to_date] = @to_date = to_date < Time.now ? to_date : Time.now
    end
  end

end
  

app/helpers/transactions_helper.rb
module TransactionsHelper

	def get_last_transaction_at
		message = ""

		branches = Branch.all
		branches.each do |branch|

			user = branch.username
			td = TransactionData.where("sender_id = ? OR receiver_id = ?", branch.clinical_id, branch.clinical_id).last
			transaction = td.transaction_record
			request_by = transaction.search_transaction.present? ? (transaction.search_transaction.fetch_by_s) : 'By System'

			message += "<span class='text-warning'>#{user}</span> Clinic Last Updated At: <span class='text-warning'>#{transaction.created_at}</span> #{request_by} <br>"

		end
		message.html_safe

	end

end

app/views/transactions/download_report.html.erb
<h2 class="mt-4 text-center text-primary">Download Report</h2>

<%= form_with url: download_report_transactions_path(format: :xlsx), method: :get, id: 'download_report_form', html: { class: 'shadow-lg p-4 rounded bg-dark mt-3' } do |form| %>
  <div class="form-group mb-3">
    <%= form.label :username, "Username", class: 'form-label text-white' %>
    <%= form.collection_select :username, Branch.all, :username, :username, { prompt: "Select a Username" }, class: 'form-control', id: 'username_select' %>
  </div>
  <div class="form-group mb-3">
    <%= form.label :transaction_from_date, "From Date", class: 'form-label text-white' %>
    <%= form.date_field :transaction_from_date, value: '', class: 'form-control light-white', id: 'transaction_from_date' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :transaction_to_date, "To Date", class: 'form-label text-white' %>
    <%= form.date_field :transaction_to_date, value: '', class: 'form-control light-white', id: 'transaction_to_date' %>
  </div>
  <%= form.hidden_field :report_type, value: 'full', id: 'report_type_field' %>

  <div class="d-flex justify-content-between mt-3">
    <%= form.submit "Full Report", class: "btn btn-primary btn-lg shadow-sm px-4", id: 'download_full_report' %>
    <%= form.submit "Rejection Report", class: "btn btn-primary btn-lg shadow-sm px-4", id: 'download_rejection_report' %>
  </div>
<% end %>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    const form = document.getElementById("download_report_form");
    const fullReportButton = document.getElementById('download_full_report');
    const rejectionReportButton = document.getElementById('download_rejection_report');
    const reportTypeField = document.getElementById('report_type_field');

    fullReportButton.addEventListener("click", function() {
      reportTypeField.value = 'full';
    });

    rejectionReportButton.addEventListener("click", function() {
      reportTypeField.value = 'rejection';
    });
  });
</script>

app/views/transactions/index.html.erb
<h2 class="mt-4 text-center text-primary">Get Transaction Data</h2>
<p class="mt-4 text-center text-primary"><%= get_last_transaction_at %></p>

<%= form_with url: fetch_transactions_transactions_path, method: :post, class: 'mt-3', id: 'transaction_form', html: { class: 'shadow-lg p-4 rounded bg-dark' } do |form| %>
  <div class="form-group mb-3">
    <%= form.label :username, "Username", class: 'form-label text-white' %>
    <%= form.collection_select :username, Branch.all, :username, :username, { prompt: "Select a Username" }, class: 'form-control', id: 'username_select' %>
  </div>
  
  <div class="form-group mb-3">
    <%= form.label :transaction_from_date, "From Date", class: 'form-label text-white' %>
    <%= form.date_field :transaction_from_date, value: '', class: 'form-control light-white', id: 'transaction_from_date' %>
  </div>

  <%= form.submit 'Send Request', class: 'btn btn-primary btn-lg btn-block mt-3 shadow-sm', id: 'submit_button' %>
<% end %>




<script>
document.addEventListener("DOMContentLoaded", function() {
  const form = document.getElementById('transaction_form');
  const fromDateInput = document.getElementById('transaction_from_date');
  const toDateInput = document.getElementById('transaction_to_date');
  const loadingIndicator = document.getElementById('loading-indicator'); // Optional: Hide/show if needed

  form.addEventListener('submit', function(event) {
    const fromDate = new Date(fromDateInput.value);
    const toDate = new Date(toDateInput.value);
    const diffTime = Math.abs(toDate - fromDate);
    const diffDays = diffTime / (1000 * 3600 * 24);

    if (diffDays > 100) {
      event.preventDefault(); // Prevent form submission
      showFlashAlert("Warning: The date range exceeds 100 days. Please adjust the dates."); // Show custom alert
      if (loadingIndicator) {
        loadingIndicator.style.display = 'none'; // Optional: Hide loading indicator if present
      }
    }
  });

  function showFlashAlert(message) {
    // Create the alert div
    const alertDiv = document.createElement('div');
    alertDiv.className = 'flash-alert';
    alertDiv.textContent = message;

    // Append the alert to the body or a specific container
    document.body.appendChild(alertDiv);

    // Display the alert
    $(alertDiv).fadeIn();

    // Automatically remove the alert after 5 seconds
    setTimeout(function() {
      $(alertDiv).fadeOut(function() {
        alertDiv.remove();
      });
    }, 5000);
  }
});


</script>

app/views/transactions/show.html.erb
<h1>Transaction Details</h1>

<table>
  <thead>
    <tr>
      <th>Sender ID</th>
      <th>Receiver ID</th>
      <th>Receiver</th>
      <th>Claim ID</th>
      <th>Transaction Date</th>
      <th>Activity Clinician</th>
      <th>Activity ID</th>
      <th>Activity Code</th>
      <th>Activity Start Date</th>
      <th>Activity Quantity</th>
      <th>Activity Net</th>
      <th>Activity Payment Amount</th>
      <th>Claim Date Settlement</th>
      <th>Claim Payment Reference</th>
      <th>RA Comments</th>
      <th>Denial Code</th> <!-- Added Denial Code Column -->
    </tr>
  </thead>
  <tbody>
    <% if @claims.present? %>
      <% @claims.each do |claim| %>
        <% if claim.present? && claim.xpath('Activity').present? %>
          <% claim.xpath('Activity').each do |activity| %>
            <tr>
              <td><%= @xml_doc.xpath('//Header/SenderID').text %></td>
              <td><%= @xml_doc.xpath('//Header/ReceiverID').text %></td>
              <td><%= claim.xpath('ProviderID').text %></td>
              <td><%= claim.xpath('ID').text %></td>
              <td><%= @xml_doc.xpath('//Header/TransactionDate').text %></td>
              <td><%= activity.xpath('Clinician').text %></td>
              <td><%= activity.xpath('ID').text %></td>
              <td><%= activity.xpath('Code').text %></td>
              <td><%= activity.xpath('Start').text %></td>
              <td><%= activity.xpath('Quantity').text %></td>
              <td><%= activity.xpath('Net').text %></td>
              <td><%= activity.xpath('PaymentAmount').text %></td>
              <td><%= claim.xpath('DateSettlement').text %></td>
              <td><%= claim.xpath('PaymentReference').text %></td>
              <td><%= claim.xpath('Comments').text %></td>
              <td><%= activity.xpath('DenialCode').text %></td> <!-- Display Denial Code here -->
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <tr>
        <td colspan="17">No transaction details available.</td>
      </tr>
    <% end %>
  </tbody>
</table>